runtime: nodejs10
env: standard
instance_class: F1
service: styleguide
handlers:
  - url: /$
    static_files: index.html
    upload: index.html
  - url: /(.*)
    static_files: \1
    upload: (.*)
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
